# For Layer 2
# apiVersion: "cilium.io/v2alpha1"
# kind: CiliumLoadBalancerIPPool
# metadata:
#   name: "test-pool-ips"
# spec:
#   blocks:
#   - cidr: "10.1.1.1/24"
---
# using nodes Ips
# apiVersion: "cilium.io/v2alpha1"
# kind: CiliumLoadBalancerIPPool
# metadata:
#   name: "test-pool-ips"
# spec:
#   blocks:
#   - cidr: "192.168.0.6/32"
#   - cidr: "192.168.0.25/32"
#   - cidr: "192.168.0.69/32"