apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: main-nfs
provisioner: example.com/external-nfs
parameters:
  server: 192.168.0.89
  path: /mnt/WDPool/Kubernetes
  readOnly: "false"
