apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: main-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.89
  path: /mnt/WDPool/Kubernetes
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true